Updated node20 and dependencies
checkdigit/currency pull request #20
Opened 2024-01-13 20:22 UTC by jpolavar

Closes #19

2024-01-30 18:31 UTC, le-cong requested changes
just a few comments

2024-01-30 18:31 UTC, le-cong commented on .github/workflows/check-published-scheduled.yml
> +    - cron: '30 20 * * *'
duplicated?

2024-01-30 18:31 UTC, le-cong commented on .github/workflows/coverage.yml
> +      - uses: actions/checkout@v3
i think we are on actions/checkout@v4 now, maybe checkout the latest public-library-template repo?

2024-01-30 18:31 UTC, le-cong commented on .github/workflows/publish.yml
> +          cache: 'npm'
same here

2024-01-30 18:31 UTC, le-cong commented on package.json
> +    "ci:test": "NODE_OPTIONS=\"--no-warnings --experimental-vm-modules\" jest --coverage=false",
remove --no-warnings?

2024-01-30 18:31 UTC, le-cong commented on package.json
> +    "moduleFileExtensions": [
is `moduleFileExtensions` necessary?

2024-01-30 18:31 UTC, le-cong commented on src/country.spec.ts
> +      /^TypeError: Country not found for code 'undefined'$/u, // This is to check for the Country not found as undefined error
this seems to be an exact match, so maybe just use plain string instead of regex?

2024-01-30 18:31 UTC, le-cong commented on src/format.ts
> +        !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping !== undefined && !resolvedOptions.useGrouping)
maybe simply as:
```
if (
        !resolvedOptions.useDecimal &&
        !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)
      ) {
```

2024-02-07 22:55 UTC, le-cong requested changes
nothing special, just noticed some differences with the PSG standards (.yml, and package.json, etc.) can you double check?

2024-02-08 04:28 UTC, jpolavar commented
> nothing special, just noticed some differences with the PSG standards (.yml, and package.json, etc.) can you double check?

We don't need prepare script  in package file so we need to change .yml files as well

2024-02-08 04:37 UTC, jpolavar commented on src/format.ts
> +      if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)) {
I updated  earlier as   ```
!resolvedOptions.useDecimal &&
        !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping !== undefined && !resolvedOptions.useGrouping) 
```based on previous PR comment https://github.com/checkdigit/currency/pull/20#discussion_r1471756343 , updated as       `if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)) {
`

2024-02-08 16:39 UTC, le-cong commented on src/format.ts
> +      if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)) {
i think my previous comment is not 100% acurate and missed the condition branch of checking `undefined`. what do you think of this:
```
if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping !== true)) {
        throw new Error('useDecimal can only be false if useCurrency and useGrouping are also false');
      }
```

2024-02-08 17:56 UTC, jpolavar commented on src/format.ts
> +      if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)) {
I added earlier```
 if (!resolvedOptions.useDecimal && !(!resolvedOptions.useCurrency && resolvedOptions.useGrouping === false)) {
        throw new Error('useDecimal can only be false if useCurrency and useGrouping are also false');
      }
``` same as the above one?

2024-02-08 18:42 UTC, le-cong approved these changes
lgtm

2024-02-14 17:47 UTC, le-cong requested changes
package.json is missing "type":"module"
there are still mismatch in CI config files such as ci.yml/coverage.yml/etc.
some diff tools can help to compare folder contents between the service and `public-library-template` repo

2024-02-14 19:00 UTC, jpolavar commented
> package.json is missing "type":"module" there are still mismatch in CI config files such as ci.yml/coverage.yml/etc. some diff tools can help to compare folder contents between the service and `public-library-template` repo

We don't have npm run prepare in our package script for currency library and so coverage and ci yaml's are different.

2024-02-14 22:39 UTC, le-cong requested changes
sorry, but i'm still not sure if it's compared with the google doc or the `public-library-template` repo, The Luke Document doesn't differenticate ci.yml/coverage.yml between services and libraries, that's why it's better to refer to the template repositories for comparison IMO.
![image](https://github.com/checkdigit/currency/assets/1005731/4f45a1d9-adac-4ac3-8a6c-347defa9b26a)

2024-02-15 04:54 UTC, jpolavar commented
> sorry, but i'm still not sure if it's compared with the google doc or the `public-library-template` repo, The Luke Document doesn't differenticate ci.yml/coverage.yml between services and libraries, that's why it's better to refer to the template repositories for comparison IMO. ![image](https://private-user-images.githubusercontent.com/1005731/304895599-4f45a1d9-adac-4ac3-8a6c-347defa9b26a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc5NzIxNDEsIm5iZiI6MTcwNzk3MTg0MSwicGF0aCI6Ii8xMDA1NzMxLzMwNDg5NTU5OS00ZjQ1YTFkOS1hZGFjLTRhYzMtOGE2Yy0zNDdkZWZhOWIyNmEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTVUMDQzNzIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjM4NmIwN2UxZjY0OWM5NmM1YjlhNGRkNzFhYTQ1NmFmOGU2YjEzMGE2NTIzN2QzOGY3MzQyMzhmODUyYTA0MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wv7jmRz7cc_8CQDVwriK6DoU8NbB6p3HOPzkY3wlhzM)

But latest doc shows that we are using `cache: 'npm' ` instead of `registry-url:` 
![Screenshot 2024-02-14 at 10 52 59 PM](https://github.com/checkdigit/currency/assets/102534666/662ed565-d492-4c4b-af93-a890c321f690)

2024-02-15 15:03 UTC, le-cong requested changes
the stuff in Luke Document doesn't cover everything, the ci.yml/coverage.yml listed there are intended for service, they are not for public repo. public repo has different files because the npm permission etc requirements are different, and that's why please look at https://github.com/checkdigit/public-library-template instead.

2024-02-15 15:16 UTC, ramaghanta commented
> the stuff in Luke Document doesn't cover everything, the ci.yml/coverage.yml listed there are intended for service, they are not for public repo. public repo has different files because the npm permission etc requirements are different, and that's why please look at https://github.com/checkdigit/public-library-template instead.

We should not have to look at multiple sources for updating dependencies and the latest standards. So, let's update the Luke document with what the workflows should be for a public repo.

2024-02-15 15:39 UTC, le-cong approved these changes
lgtm

2024-02-15 15:44 UTC, merged